const actionTypes = {
  NEW_MOVE: "NEW_MOVE",
  GENERATE_CANDIDATE_MOVES: "GENERATE_CANDIDATE_MOVES",
  CLEAR_CANDIDATE_MOVES: "CLEAR_CANDIDATE_MOVES",
  PROMOTION_OPEN: "PROMOTION_OPEN",
  PROMOTION_CLOSE: "PROMOTION_CLOSE",
  CAN_CASTLE: "CAN_CASTLE",
  NEW_GAME: "NEW_GAME",
  DETECT_STALEMATE: "DETECT_STALEMATE",
  INSUFFICIENT_MATERIAL: "INSUFFICIENT_MATERIAL",
  CHECKMATE: "CHECKMATE",
  TAKEBACK: "TAKEBACK ",
  FIFTY_MOVE: "FIFTY MOVE",
  THREE_FOLD: "THREE_FOLD",
  INCREASE: "INCREASE",
};

export default actionTypes;
